#!/bin/sh
set -e
if [ "$TARGET_ARCH" == "arm*" ]; then
	export CARGO_NET_GIT_FETCH_WITH_CLI=true
fi
cargo build --release --locked --target-dir target
scripts/mkmo locale/
strip target/release/paru
tar --zstd -cfparu.tar.zst  man completions paru.conf locale -C target/release paru
