name: Build Release
on:
  push:
    tags:
      - v*


jobs:
  build-releases:
    strategy:
      matrix:
        arch:
          [
            "x86_64",
            "aarch64",
            "armv7h"
          ]
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'paru/'
      - name: Get arch-bootstrap
        uses: actions/checkout@v3
        with:
          path: 'bootstrap/'
          repository: 'tokland/arch-bootstrap'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Build ${{ matrix.arch }} release
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install bash xz-utils zstd gzip gawk sed fakeroot fakechroot rsync
          fakechroot -- fakeroot -- bash bootstrap/arch-bootstrap.sh -a ${{ matrix.arch }} -q rootfs/
          fakeroot -- rsync -a paru/ rootfs/paru/
          fakechroot -- fakeroot -- chroot rootfs/ /paru/scripts/chrootbuild
          mkdir -p artifacts
          mv paru/paru.tar.zst artifacts/paru-${{ matrix.arch }}.tar.zst
      - uses: actions/upload-artifact@v2
        with:
          name: paru-${{ matrix.arch }}
          path: artifacts

  create_release:
    name: Create release from this build
    needs: [build-releases]
    runs-on: ubuntu-latest
    steps:
      - name: Read info
        id: tags
        shell: bash
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - uses: actions/download-artifact@v2
      - name: Tag Assets with Version
        id: tag-assets
        run: |
          find . -type f -name 'paru-*.tar.zst' | while read file; do
            mv "$file" "./paru-${{ steps.tags.outputs.tag }}-${file##*paru-}"
          done
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tags.outputs.tag }}
          draft: true
          prerelease: false
          files: |
            paru-*.tar.zst
